seajs_path: seajs/seajs/2.1.1/sea.js
family: klog
output:
  relative:
    - blogs/show.js
    - admin/blogs/form.js
    - admin/categories/index.js
    - admin/comments/index.js
    - admin/pages/form.js
    - admin/settings/sidebar/edit.js
    - admin/index.js
    - admin/common/pop-confirm.js
  all: []
alias:
  $: gallery/jquery/1.8.3/jquery
  _: gallery/underscore/1.4.4/underscore
  backbone: gallery/backbone/0.9.10/backbone
  backbone.marionette: gallery/backbone.marionette/1.0.4/backbone.marionette
  swfupload: gallery/swfupload/2.2.0/swfupload
  events: gallery/events/1.0.0/events
  tab: gallery/tab/0.0.1/tab
  modal: gallery/modal/0.0.1/modal
  jquery-ujs: gallery/jquery-ujs/2.2.1/jquery-ujs
  jquery.color: jquery/color/2.1.2/color
